[package]
name = "DeepFilterLib"
version = "0.2.0"
authors = ["Hendrik Schröter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdf"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = ["transforms"], version = "0.2.0" }
pyo3 = { version = "^0.16", features = ["extension-module"]}
numpy = "^0.16"
ndarray = "^0.15"
