[package]
name = "DeepFilterLib"
version = "0.3.1"
authors = ["Hendrik Schröter"]
edition = "2021"

[lib]
name = "libdf"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = ["transforms", "logging"], path = "../libDF" }
pyo3 = { version = "0.17.1", features = ["extension-module"]}
numpy = "0.17.1"
ndarray = "^0.15"
