name: Test DF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["publish-pypi-wheels"]
    branches: [main]
    types:
      - completed
  schedule:
    - cron: '0 18 * * 0'

jobs:
  test-df-output:
    if: "!contains(github.event.head_commit.message, 'v*[0-9]+.[0-9]+.[0-9]+')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        is_pr:
          - ${{ github.event_name == 'pull_request' }}
        include:
          - os: "ubuntu-latest"
        exclude:
          - os: "macos-latest"
            is_pr: true  # Run only linux on PR
          - os: "windows-latest"
            is_pr: true  # Run only linux on PR
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      # Aditionally test against original matlab composite metrics
      - name: Set Extra Dependency Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "EXTRA=-E semetrics" >> $GITHUB_ENV
      # Soundfile backend for torchaudio
      - name: Set Extra Dependency Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "EXTRA=-E soundfile" >> $GITHUB_ENV
      - name: Rust cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with: {profile: "minimal", toolchain: "stable"}
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Load cached Poetry installation
        if: matrix.os != 'windows-latest'
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.python }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: |
            .venv
            ~/.venv
            DeepFilterNet/.venv
          key: venv-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install runtime dependencies and DeepFilterNet
        working-directory: DeepFilterNet
        run: |
          poetry --version
          poetry env use ${{matrix.python}}
          poetry install --no-interaction -E dnsmos -E eval ${{env.EXTRA}}
          poetry run poe install-torch-cpu
      - name: Install Octave
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install --no-install-recommends octave
      - name: Run DF Test
        working-directory: DeepFilterNet
        run: |
          source $VENV
          python df/scripts/test_df.py
      - name: Test deepFilter script
        env:
          DNS_AUTH_KEY: ${{ secrets.DNS_AUTH_KEY }}
        run: |
          source ./DeepFilterNet/$VENV
          mkdir ./out
          deepFilter ./assets/noisy_snr0.wav -m ./DeepFilterNet/pretrained_models/DeepFilterNet2/ -o out/
          python DeepFilterNet/df/scripts/dnsmos.py assets/noisy_snr0.wav -t 2.9511659145355225
          python DeepFilterNet/df/scripts/dnsmos.py out/noisy_snr0_DeepFilterNet2.wav -t 3.7940118312835693
      - uses: actions/upload-artifact@v2
        with:
          name: enhanced_noisy
          path: out/*wav
